### PR TITLE
Two Column Layout Implementation

### PR DESCRIPTION
**Pull request by math-marcellino**
### 1. Implement Navigation as Component
image

### 2. Implement Two Column Layout in ETHRISE Page 
- Leverage Tab
image
- Lend Tab
image

### CODE REVIEW

**Comment by pyk** [comment]
@math-marcellino btw I think it's better to use 2 columns when the screen is larger than 1024px only

Screen Shot 2022-03-17 at 02 13 50
Screen Shot 2022-03-17 at 02 13 34

cc @ayikfour

**Comment by math-marcellino** [comment]
> @math-marcellino btw I think it's better to use 2 columns when the screen is larger than 1024px only
> 
> Screen Shot 2022-03-17 at 02 13 50
> 
> Screen Shot 2022-03-17 at 02 13 34
> 
> cc @ayikfour

Okay sir, I have pushed the latest update. Please kindly check it 🙏

**Comment by pyk** [comment]
Nice.

@math-marcellino @ayikfour One more thing, how about we max the Information & Backing card component max width same as the previous one coz I think in the larger screen it looks too wide. Wdyt guys?

Screen Shot 2022-03-17 at 14 40 14

**Comment by ayikfour** [comment]
Just provided the width specs in here guys: https://www.figma.com/file/t4BnIO0LHqk10vmKZ4kRV4/Website-%E2%80%93-1.0?node-id=1862%3A82275

Agreed on we should set max-width as on the 1280px viewport.

**Comment by pyk** [comment]
@ayikfour niceee. thanks mas!

cc @math-marcellino

**Comment by math-marcellino** [comment]
@pyk The width has been fixed, please kindly check it sir, thank you 🙏

**Comment by pyk** [comment]
@math-marcellino LGTM! tysm!

**Pull request merged**
