### PR TITLE
refactor portofolio page

### PR DESCRIPTION
**Pull request by asaadam**
refactor portofolio page

### CODE REVIEW

**Comment by math-marcellino** [comment]
@asaadam LGTM sir, but I think the `BackgroundGradient` component should be in `/modules/portfolio/component` instead of in `/uikit`, because it's a bit different than the one in `ethrisePage`. It is also only used in `portfolio` page too. Wdyt?

**Comment by pyk** [comment]
@asaadam btw what is `tsbuildinfo` used for?

**Review by pyk — CHANGES_REQUESTED** [review]
Just need to confirm about `tsbuildinfo`, otherwise LGTM

**Comment by asaadam** [comment]
> @asaadam LGTM sir, but I think the `BackgroundGradient` component should be in `/modules/portfolio/component` instead of in `/uikit`, because it's a bit different than the one in `ethrisePage`. It is also only used in `portfolio` page too. Wdyt?

hmm, i see,
but i think i can be reuse in the future

WDYT?

**Comment by asaadam** [comment]
> Just need to confirm about `tsbuildinfo`, otherwise LGTM

my bad, it should be gitignored.

**Review by pyk — APPROVED** [review]

**Comment by pyk** [comment]
Thanks @asaadam!

**Comment by pyk** [comment]
Wait for @math-marcellino yes

**Comment by math-marcellino** [comment]
> > @asaadam LGTM sir, but I think the `BackgroundGradient` component should be in `/modules/portfolio/component` instead of in `/uikit`, because it's a bit different than the one in `ethrisePage`. It is also only used in `portfolio` page too. Wdyt?
> 
> hmm, i see, but i think i can be reuse in the future
> 
> WDYT?

Oh I see, all good then sir..

**Review by math-marcellino — APPROVED** [review]

**Review by math-marcellino — APPROVED** [review]

**Pull request merged**
