### PR TITLE
Temporary Portofolio v2 Implementation (#159)

### PR DESCRIPTION
**Pull request by math-marcellino**
# #159 Temporary Portofolio v2 Implementation

## 1. Implement Desktop Layout
image
image

##2. Implement Mobile Layout
image
image

## 3. Refactor and Update `NoPortofolioWarn` Component
Adjust styling based on figma & styling logic from tailwind

## 4. TODO: Get Changes Value
The `Changes` in Portofolio Page is currently still hard coded, I'm still searching for a way to get the all time changes for user's portofolio. Maybe we can change it to `Daily Changes` for the time being so it can be deployed to production(?)

### CODE REVIEW

**Comment by math-marcellino** [comment]
# Get All-time Changes Value
I have found a way to get the all-time changes value for the user's token. But I faced some problems, which are :
- I can't get all-time changes for vault token, because there is no `block_number` properties in `vault historical data` yet.
- All-time changes for leveraged token (ETHRISE) is calculated from 24 February 2022, because the `snapshot service` for `leveraged token historical data` has just started to record `block_number` in that date.

Current preview of `PortofolioPage` can be seen in picture below. Currently the `Total Value` and `Changes` represent the value for ETHRISE only.
image

**Comment by pyk** [comment]
@math-marcellino I think we need to make this simple. 

What about we use "Last 24hr" instead of "Changes" ? @ayikfour @math-marcellino 

So mathew can use similar technique like in the chart

**Comment by ayikfour** [comment]
Oh, i think I'm misunderstood this one. 

So if we use the same mechanism with chart in product detail we can have it? I thought we don't have that data yet

But cmiiw guys @pyk @math-marcellino

**Comment by pyk** [comment]
I will merge this first and revised it later

**Pull request merged**
