### PR TITLE
RIS 108 Jumbotron #3

### PR DESCRIPTION
**Pull request by math-marcellino**
## 1. Implemented:
- Third Jumbotron layout for desktop & mobile
- Gradients in third jumbotron
- Grid background in third jumbotron

### CODE REVIEW

**Comment by asaadam** [comment]
@math-marcellino 
`I'm not sure if the way I implemented the gradient components is the best practice, so I'll take any suggestion guys hehe`

AFAIK, div it's better than using SVG or png. 
LGTM, lets wait @ayikfour and @pyk to review it

**Comment by math-marcellino** [comment]
> @math-marcellino `I'm not sure if the way I implemented the gradient components is the best practice, so I'll take any suggestion guys hehe`
> 
> AFAIK, div it's better than using SVG or png. LGTM, lets wait @ayikfour and @pyk to review it

Ohh sorry, btw what I mean is the css implementation sir haha

**Comment by asaadam** [comment]
> > @math-marcellino `I'm not sure if the way I implemented the gradient components is the best practice, so I'll take any suggestion guys hehe`
> > AFAIK, div it's better than using SVG or png. LGTM, lets wait @ayikfour and @pyk to review it
> 
> Ohh sorry, btw what I mean is the css implementation sir haha

it's fine matthew

**Comment by math-marcellino** [comment]
I have fixed the gradients color & positioning + the audits for jumbotron #3 mentioned in RIS-222
Please kindly check it sir @ayikfour and let me know if there is something else need to be fixed..
https://234eb358.frontend-3mt.pages.dev/home/v2

**Pull request merged**
