### PR TITLE
[Bug-Fix] fix disconnect wallet button  

### PR DESCRIPTION
**Pull request by asaadam**
issue : [issue](https://github.com/risedle/interface/issues/11)
the idea is to disconnect wallets, it's to store wallet data on local storage. 

the metamask wallet actually still connected to our apps, but we can add further logic to disallow users to make interaction before they connect their wallet again. 

this approach was implemented on opensea.io, as you can see on this video 
https://www.loom.com/share/e26d351298ff4a13987212920bd9d9c7

the difference is, opensea using `session` where this implementation uses `localstorage` to store wallet data.

this's a demo from this implementation. 
https://www.loom.com/share/99ba0792a65740e388357ef217e5d587

i also move `useEthers();` to `ConnectMetamask.tsx`, so it's no longer need to passing props

### CODE REVIEW

**Comment by pyk** [comment]
@asaadam ser, The idea we use `useEthers()` on every page is to make sure that all components is auto-refreshed when user is connected/disconnected to the wallet.

**Comment by asaadam** [comment]
@pyk  can you give an example case when the component is not auto-refreshed? 

i will check it first

**Comment by pyk** [comment]
@asaadam here is step by step to reproduce it:

1. Go to https://demo.risedle.com/vault/deposit (make sure u have disconnected your wallet)
2. Connect your wallet, the page will automatically reloaded

**Comment by asaadam** [comment]
@pyk 
https://www.loom.com/share/80b3cc7e0ead4f46a32de4516dbc8a11

i thinks it's looking good

**Comment by pyk** [comment]
@asaadam if u goto `/vault/deposit` after connecting your wallet, ur wallet will not recognized

**Comment by asaadam** [comment]
https://www.loom.com/share/486fa54218234222a0b39af2e90a4cdb
@pyk it's also looking good ser

**Pull request closed without merging**
