### PR TITLE
add header policy

### PR DESCRIPTION
**Pull request by asaadam**
add header policy
https://linear.app/risedle/issue/RIS-216/update-security-on-frontend

Before 
image

After
image

### CODE REVIEW

**Review by math-marcellino — APPROVED** [review]
LGTM sir, let's wait for @pyk

**Comment by pyk** [comment]
It's breaking the app 

Screen Shot 2022-06-15 at 21 21 38

https://265b3510.frontend-3mt.pages.dev/markets

**Review by pyk — CHANGES_REQUESTED** [review]
This still breaking the app.

also, please set the `object-src` to none.

Relevant tools:
- https://csp-evaluator.withgoogle.com/
- https://chrome.google.com/webstore/detail/content-security-policy-c/ahlnecfloencbkpfnpljbojmjkfgnmdc

**Comment by asaadam** [comment]
@pyk please check it agian ser

**Review by pyk — APPROVED** [review]
LGTM

**Pull request merged**
